name: Node application

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name:
          run: |
            touch .env
            echo ${{ secrets.MONGODB }} >> .env
            cat .env

      - uses: actions/checkout@v2
      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_CREDENTIALS }}
